In [17]:
import pandas as pd
import sqlite3
conn = sqlite3.connect('proj3.sqlite')
c = conn.cursor()

In [18]:
c.execute('''CREATE TABLE crash_data (county PK VARCHAR,total_fatal_crashes int,total_injury_crashes int,
alcohol_involved_fatal int,alcohol_involved_injury int)''')

In [19]:
c.execute('''CREATE TABLE fatal_crash_data (county PK VARCHAR,'2010' int,"2011" int,"2012" int,"2013" int,"2014" int,"2015" int,
"2016" int,"2017" int,"2018" int,"2019" int)''')

In [20]:
c.execute('''CREATE TABLE fatal_crash_by_month_data (county PK VARCHAR,'2010' int,'2011' int,'2012' int,'2013' int,'2014' int,
'2015' int,'2016' int,'2017' int,'2018' int,'2019' int,total int)''')

In [21]:
crash_data_tab = pd.read_csv('crash_data.csv')

In [8]:
crash_data_tab

,county,total_fatal_crashes,total_injury_crashes,alcohol_involved_fatal,alcohol_involved_injury
0,Alameda,90,"7,905",28,655
1,Alpine,2,33,0,4
2,Amador,13,196,4,38
3,Butte,33,920,9,143
4,Calaveras,10,226,4,45
5,Colusa,9,142,1,21
6,Contra Costa,69,"4,353",27,492
7,Del Norte,8,139,1,19
8,El Dorado,27,615,11,103
9,Fresno,122,"2,669",34,305
10,Glenn,5,105,1,15
11,Humboldt,20,574,14,100
12,Imperial,29,522,7,60
13,Inyo,9,100,1,10
14,Kern,138,"3,721",48,435
15,Kings,13,558,6,78
16,Lake,15,271,5,55
17,Lassen,6,93,0,15
18,Los Angeles,683,"60,183",202,"4,784"
19,Madera,35,658,9,100
20,Marin,20,"1,018",7,109
21,Mariposa,4,70,2,8
22,Mendocino,21,375,9,73
23,Merced,47,"1,448",13,183
24,Modoc,6,51,0,4
25,Mono,5,58,2,7
26,Monterey,32,"1,925",14,287
27,Napa,17,742,5,100
28,Nevada,10,396,2,71
29,Orange,164,"12,230",61,"1,138"
30,Placer,24,"1,565",7,180
31,Plumas,3,114,1,30
32,Riverside,269,"10,109",101,"1,077"
33,Sacramento,164,"8,602",48,819
34,San Benito,11,279,4,28
35,San Bernardino,302,"10,811",96,"1,156"
36,San Diego,239,"14,084",80,"1,714"
37,San Francisco,34,"3,926",4,359
38,San Joaquin,111,"4,220",31,478
39,San Luis Obispo,31,"1,043",11,137
40,San Mateo,27,"2,953",5,305
41,Santa Barbara,33,"1,785",9,246
42,Santa Clara,124,"7,621",34,769
43,Santa Cruz,19,"1,136",7,206
44,Shasta,34,747,12,87
45,Sierra,3,32,0,7
46,Siskiyou,9,241,1,32
47,Solano,43,"1,911",12,169
48,Sonoma,36,"2,261",11,308
49,Stanislaus,63,"3,134",23,362
50,Sutter,22,513,6,54
51,Tehama,15,264,6,45
52,Trinity,8,84,3,14
53,Tulare,60,"1,910",19,240
54,Tuolumne,12,389,5,65
55,Ventura,43,"3,862",13,404
56,Yolo,24,962,8,91
57,Yuba,13,357,3,41
58,Statewide Total,"3,438","187,211","1,087","18,880"

In [22]:
fatal_crash_by_month_data_tab = pd.read_csv('fatal_crash_by_month_data.csv')

In [23]:
fatal_crash_data_tab = pd.read_csv('fatal_crash_data.csv')

In [24]:
crash_data_tab.to_sql('crash_data', conn, if_exists='replace', index = False)

59

In [25]:
fatal_crash_data_tab.to_sql('fatal_crash_data', conn, if_exists='replace', index = False)

59

In [26]:
fatal_crash_by_month_data_tab.to_sql('fatal_crash_by_month_data', conn, if_exists='replace', index = False)

59

In [14]:
c.execute('''SELECT * FROM crash_data''').fetchall()

[('Alameda', '90', '7,905', '28', '655'),
 ('Alpine', '2', '33', '0', '4'),
 ('Amador', '13', '196', '4', '38'),
 ('Butte', '33', '920', '9', '143'),
 ('Calaveras', '10', '226', '4', '45'),
 ('Colusa', '9', '142', '1', '21'),
 ('Contra Costa', '69', '4,353', '27', '492'),
 ('Del Norte', '8', '139', '1', '19'),
 ('El Dorado', '27', '615', '11', '103'),
 ('Fresno', '122', '2,669', '34', '305'),
 ('Glenn', '5', '105', '1', '15'),
 ('Humboldt', '20', '574', '14', '100'),
 ('Imperial', '29', '522', '7', '60'),
 ('Inyo', '9', '100', '1', '10'),
 ('Kern', '138', '3,721', '48', '435'),
 ('Kings', '13', '558', '6', '78'),
 ('Lake', '15', '271', '5', '55'),
 ('Lassen', '6', '93', '0', '15'),
 ('Los Angeles', '683', '60,183', '202', '4,784'),
 ('Madera', '35', '658', '9', '100'),
 ('Marin', '20', '1,018', '7', '109'),
 ('Mariposa', '4', '70', '2', '8'),
 ('Mendocino', '21', '375', '9', '73'),
 ('Merced', '47', '1,448', '13', '183'),
 ('Modoc', '6', '51', '0', '4'),
 ('Mono', '5', '58', '2', '7'),
 ('Monterey', '32', '1,925', '14', '287'),
 ('Napa', '17', '742', '5', '100'),
 ('Nevada', '10', '396', '2', '71'),
 ('Orange', '164', '12,230', '61', '1,138'),
 ('Placer', '24', '1,565', '7', '180'),
 ('Plumas', '3', '114', '1', '30'),
 ('Riverside', '269', '10,109', '101', '1,077'),
 ('Sacramento', '164', '8,602', '48', '819'),
 ('San Benito', '11', '279', '4', '28'),
 ('San Bernardino', '302', '10,811', '96', '1,156'),
 ('San Diego', '239', '14,084', '80', '1,714'),
 ('San Francisco', '34', '3,926', '4', '359'),
 ('San Joaquin', '111', '4,220', '31', '478'),
 ('San Luis Obispo', '31', '1,043', '11', '137'),
 ('San Mateo', '27', '2,953', '5', '305'),
 ('Santa Barbara', '33', '1,785', '9', '246'),
 ('Santa Clara', '124', '7,621', '34', '769'),
 ('Santa Cruz', '19', '1,136', '7', '206'),
 ('Shasta', '34', '747', '12', '87'),
 ('Sierra', '3', '32', '0', '7'),
 ('Siskiyou', '9', '241', '1', '32'),
 ('Solano', '43', '1,911', '12', '169'),
 ('Sonoma', '36', '2,261', '11', '308'),
 ('Stanislaus', '63', '3,134', '23', '362'),
 ('Sutter', '22', '513', '6', '54'),
 ('Tehama', '15', '264', '6', '45'),
 ('Trinity', '8', '84', '3', '14'),
 ('Tulare', '60', '1,910', '19', '240'),
 ('Tuolumne', '12', '389', '5', '65'),
 ('Ventura', '43', '3,862', '13', '404'),
 ('Yolo', '24', '962', '8', '91'),
 ('Yuba', '13', '357', '3', '41'),
 ('Statewide Total', '3,438', '187,211', '1,087', '18,880')]

In [15]:
c.execute('''SELECT * FROM fatal_crash_data''').fetchall()

[('Alameda', '62', '57', '72', '82', '83', '87', '78', '97', '78', '90'),
 ('Alpine', '1', '2', '1', '1', '1', '2', '4', '4', '2', '2'),
 ('Amador', '6', '11', '6', '5', '7', '7', '12', '11', '9', '13'),
 ('Butte', '38', '19', '23', '19', '22', '31', '32', '33', '36', '33'),
 ('Calaveras', '11', '8', '9', '7', '8', '11', '8', '19', '12', '10'),
 ('Colusa', '6', '7', '4', '8', '3', '5', '5', '11', '10', '9'),
 ('Contra Costa', '40', '47', '57', '48', '43', '72', '78', '62', '73', '69'),
 ('Del Norte', '6', '11', '7', '8', '9', '14', '8', '6', '9', '8'),
 ('El Dorado', '16', '18', '19', '23', '19', '24', '20', '24', '30', '27'),
 ('Fresno',
  '95',
  '111',
  '106',
  '101',
  '118',
  '89',
  '135',
  '137',
  '108',
  '122'),
 ('Glenn', '7', '3', '4', '4', '3', '6', '8', '8', '7', '5'),
 ('Humboldt', '16', '26', '28', '28', '27', '24', '21', '33', '20', '20'),
 ('Imperial', '24', '12', '29', '26', '35', '26', '28', '24', '31', '29'),
 ('Inyo', '6', '7', '6', '3', '0', '5', '7', '8', '0', '9'),
 ('Kern', '96', '93', '114', '122', '103', '123', '134', '169', '127', '138'),
 ('Kings', '18', '11', '21', '15', '12', '29', '26', '23', '16', '13'),
 ('Lake', '15', '15', '13', '19', '7', '17', '14', '15', '10', '15'),
 ('Lassen', '9', '7', '8', '7', '5', '7', '7', '8', '10', '6'),
 ('Los Angeles',
  '530',
  '513',
  '585',
  '585',
  '606',
  '618',
  '782',
  '715',
  '693',
  '683'),
 ('Madera', '23', '23', '23', '18', '28', '26', '35', '21', '23', '35'),
 ('Marin', '2', '6', '10', '13', '8', '7', '10', '14', '16', '20'),
 ('Mariposa', '4', '3', '5', '3', '4', '3', '4', '6', '3', '4'),
 ('Mendocino', '19', '17', '19', '15', '16', '9', '24', '27', '31', '21'),
 ('Merced', '30', '39', '40', '45', '34', '46', '60', '62', '49', '47'),
 ('Modoc', '1', '5', '1', '3', '3', '3', '1', '0', '2', '6'),
 ('Mono', '5', '1', '5', '1', '5', '5', '1', '4', '7', '5'),
 ('Monterey', '33', '46', '26', '30', '30', '47', '50', '54', '44', '32'),
 ('Napa', '9', '8', '7', '15', '7', '14', '12', '15', '14', '17'),
 ('Nevada', '10', '6', '17', '13', '5', '13', '12', '14', '16', '10'),
 ('Orange',
  '100',
  '128',
  '148',
  '165',
  '165',
  '178',
  '196',
  '197',
  '192',
  '164'),
 ('Placer', '23', '24', '27', '19', '13', '21', '37', '30', '27', '24'),
 ('Plumas', '4', '9', '8', '2', '5', '4', '8', '6', '4', '3'),
 ('Riverside',
  '190',
  '186',
  '202',
  '208',
  '225',
  '237',
  '264',
  '283',
  '289',
  '269'),
 ('Sacramento',
  '118',
  '105',
  '97',
  '116',
  '100',
  '124',
  '153',
  '157',
  '134',
  '164'),
 ('San Benito', '4', '5', '9', '7', '8', '8', '11', '8', '12', '11'),
 ('San Bernardino',
  '203',
  '209',
  '217',
  '235',
  '257',
  '237',
  '254',
  '308',
  '289',
  '302'),
 ('San Diego',
  '174',
  '196',
  '206',
  '193',
  '217',
  '233',
  '230',
  '222',
  '253',
  '239'),
 ('San Francisco', '29', '33', '31', '34', '30', '38', '35', '25', '28', '34'),
 ('San Joaquin',
  '75',
  '79',
  '56',
  '81',
  '81',
  '91',
  '111',
  '105',
  '104',
  '111'),
 ('San Luis Obispo',
  '17',
  '21',
  '27',
  '25',
  '28',
  '33',
  '31',
  '32',
  '37',
  '31'),
 ('San Mateo', '17', '47', '36', '44', '24', '33', '46', '29', '29', '27'),
 ('Santa Barbara', '29', '26', '30', '30', '19', '37', '31', '33', '31', '33'),
 ('Santa Clara',
  '81',
  '91',
  '82',
  '93',
  '104',
  '126',
  '106',
  '111',
  '116',
  '124'),
 ('Santa Cruz', '10', '8', '11', '13', '20', '16', '21', '16', '22', '19'),
 ('Shasta', '19', '25', '25', '24', '25', '38', '25', '29', '29', '34'),
 ('Sierra', '3', '2', '3', '2', '0', '1', '1', '3', '1', '3'),
 ('Siskiyou', '8', '12', '13', '5', '8', '11', '10', '15', '14', '9'),
 ('Solano', '28', '27', '17', '36', '45', '42', '35', '32', '53', '43'),
 ('Sonoma', '36', '28', '35', '29', '35', '45', '42', '42', '38', '36'),
 ('Stanislaus', '46', '52', '43', '51', '53', '48', '75', '72', '79', '63'),
 ('Sutter', '13', '11', '8', '10', '11', '16', '7', '20', '19', '22'),
 ('Tehama', '12', '13', '10', '10', '12', '17', '16', '11', '20', '15'),
 ('Trinity', '7', '5', '1', '4', '6', '4', '8', '5', '8', '8'),
 ('Tulare', '64', '52', '61', '50', '59', '67', '74', '77', '63', '60'),
 ('Tuolumne', '7', '9', '6', '8', '10', '10', '9', '13', '7', '12'),
 ('Ventura', '40', '64', '47', '61', '46', '50', '54', '48', '51', '43'),
 ('Yolo', '12', '18', '19', '17', '17', '23', '34', '19', '25', '24'),
 ('Yuba', '13', '11', '18', '14', '8', '10', '12', '10', '18', '13'),
 ('Total',
  '2,520',
  '2,628',
  '2,758',
  '2,853',
  '2,882',
  '3,168',
  '3,552',
  '3,582',
  '3,478',
  '3,438')]

In [16]:
c.execute('''SELECT * FROM fatal_crash_by_month_data''').fetchall()

[('Alameda',
  9.0,
  9.0,
  7.0,
  5.0,
  10.0,
  3.0,
  12.0,
  8.0,
  6.0,
  7.0,
  7.0,
  7.0,
  '90'),
 ('Alpine', 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, '2'),
 ('Amador', 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 3.0, 2.0, 1.0, 1.0, 0.0, 2.0, '13'),
 ('Butte', 3.0, 2.0, 1.0, 2.0, 4.0, 4.0, 2.0, 4.0, 2.0, 4.0, 2.0, 3.0, '33'),
 ('Calaveras',
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  2.0,
  2.0,
  2.0,
  3.0,
  0.0,
  '10'),
 ('Colusa', 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0, 1.0, 1.0, '9'),
 ('Contra Costa',
  3.0,
  8.0,
  6.0,
  4.0,
  5.0,
  9.0,
  6.0,
  7.0,
  8.0,
  4.0,
  3.0,
  6.0,
  '69'),
 ('Del Norte',
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  0.0,
  2.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  '8'),
 ('El Dorado',
  5.0,
  6.0,
  0.0,
  2.0,
  0.0,
  4.0,
  2.0,
  1.0,
  3.0,
  3.0,
  1.0,
  0.0,
  '27'),
 ('Fresno',
  12.0,
  13.0,
  7.0,
  11.0,
  4.0,
  5.0,
  12.0,
  17.0,
  13.0,
  9.0,
  9.0,
  10.0,
  '122'),
 ('Glenn', 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, '5'),
 ('Humboldt',
  3.0,
  1.0,
  0.0,
  0.0,
  2.0,
  3.0,
  1.0,
  2.0,
  5.0,
  1.0,
  1.0,
  1.0,
  '20'),
 ('Imperial',
  5.0,
  3.0,
  1.0,
  2.0,
  2.0,
  3.0,
  1.0,
  1.0,
  2.0,
  2.0,
  3.0,
  4.0,
  '29'),
 ('Inyo', 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 2.0, 2.0, 0.0, 0.0, 1.0, 1.0, '9'),
 ('Kern',
  11.0,
  13.0,
  4.0,
  12.0,
  7.0,
  13.0,
  12.0,
  15.0,
  8.0,
  16.0,
  12.0,
  15.0,
  '138'),
 ('Kings', 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 4.0, 2.0, 3.0, 0.0, 1.0, '13'),
 ('Lake', 0.0, 1.0, 0.0, 1.0, 2.0, 1.0, 0.0, 1.0, 0.0, 2.0, 5.0, 2.0, '15'),
 ('Lassen', 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, '6'),
 ('Los Angeles',
  52.0,
  58.0,
  51.0,
  66.0,
  48.0,
  54.0,
  64.0,
  57.0,
  48.0,
  61.0,
  72.0,
  52.0,
  '683'),
 ('Madera', 4.0, 2.0, 1.0, 2.0, 7.0, 1.0, 3.0, 2.0, 3.0, 4.0, 3.0, 3.0, '35'),
 ('Marin', 3.0, 1.0, 1.0, 4.0, 1.0, 1.0, 2.0, 0.0, 5.0, 0.0, 1.0, 1.0, '20'),
 ('Mariposa', 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, '4'),
 ('Mendocino',
  3.0,
  1.0,
  1.0,
  2.0,
  2.0,
  2.0,
  4.0,
  0.0,
  3.0,
  0.0,
  2.0,
  1.0,
  '21'),
 ('Merced', 3.0, 2.0, 6.0, 2.0, 3.0, 5.0, 0.0, 3.0, 5.0, 7.0, 6.0, 5.0, '47'),
 ('Modoc', 0.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, '6'),
 ('Mono', 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, '5'),
 ('Monterey',
  2.0,
  2.0,
  4.0,
  4.0,
  2.0,
  4.0,
  2.0,
  1.0,
  2.0,
  2.0,
  4.0,
  3.0,
  '32'),
 ('Napa', 1.0, 0.0, 1.0, 1.0, 0.0, 2.0, 1.0, 3.0, 6.0, 0.0, 2.0, 0.0, '17'),
 ('Nevada', 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 2.0, 1.0, 1.0, '10'),
 ('Orange',
  17.0,
  10.0,
  10.0,
  11.0,
  9.0,
  21.0,
  14.0,
  13.0,
  10.0,
  17.0,
  18.0,
  14.0,
  '164'),
 ('Placer', 2.0, 0.0, 4.0, 1.0, 1.0, 1.0, 0.0, 3.0, 1.0, 5.0, 2.0, 4.0, '24'),
 ('Plumas', 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, '3'),
 ('Riverside',
  28.0,
  8.0,
  20.0,
  24.0,
  24.0,
  29.0,
  21.0,
  21.0,
  23.0,
  20.0,
  33.0,
  18.0,
  '269'),
 ('Sacramento',
  11.0,
  6.0,
  14.0,
  11.0,
  13.0,
  18.0,
  14.0,
  16.0,
  16.0,
  13.0,
  15.0,
  17.0,
  '164'),
 ('San Benito',
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  2.0,
  2.0,
  1.0,
  1.0,
  2.0,
  0.0,
  1.0,
  '11'),
 ('San Bernardino',
  22.0,
  14.0,
  19.0,
  20.0,
  36.0,
  26.0,
  30.0,
  19.0,
  24.0,
  21.0,
  42.0,
  29.0,
  '302'),
 ('San Diego',
  14.0,
  20.0,
  25.0,
  19.0,
  18.0,
  17.0,
  14.0,
  23.0,
  15.0,
  23.0,
  28.0,
  23.0,
  '239'),
 ('San Francisco',
  3.0,
  3.0,
  6.0,
  2.0,
  4.0,
  3.0,
  3.0,
  1.0,
  1.0,
  4.0,
  1.0,
  3.0,
  '34'),
 ('San Joaquin',
  7.0,
  12.0,
  7.0,
  7.0,
  10.0,
  8.0,
  9.0,
  10.0,
  15.0,
  3.0,
  11.0,
  12.0,
  '111'),
 ('San Luis Obispo',
  2.0,
  1.0,
  4.0,
  1.0,
  0.0,
  1.0,
  6.0,
  3.0,
  3.0,
  5.0,
  2.0,
  3.0,
  '31'),
 ('San Mateo',
  5.0,
  3.0,
  1.0,
  4.0,
  3.0,
  2.0,
  2.0,
  1.0,
  3.0,
  1.0,
  1.0,
  1.0,
  '27'),
 ('Santa Barbara',
  5.0,
  3.0,
  2.0,
  4.0,
  0.0,
  4.0,
  3.0,
  0.0,
  4.0,
  2.0,
  2.0,
  4.0,
  '33'),
 ('Santa Clara',
  12.0,
  7.0,
  9.0,
  6.0,
  11.0,
  12.0,
  6.0,
  10.0,
  13.0,
  10.0,
  14.0,
  14.0,
  '124'),
 ('Santa Cruz',
  0.0,
  3.0,
  2.0,
  0.0,
  3.0,
  1.0,
  0.0,
  4.0,
  4.0,
  2.0,
  0.0,
  0.0,
  '19'),
 ('Shasta', 2.0, 1.0, 3.0, 0.0, 1.0, 6.0, 2.0, 5.0, 4.0, 2.0, 5.0, 3.0, '34'),
 ('Sierra', 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, '3'),
 ('Siskiyou', 0.0, 2.0, 3.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, '9'),
 ('Solano', 7.0, 4.0, 2.0, 3.0, 5.0, 2.0, 2.0, 3.0, 8.0, 3.0, 3.0, 1.0, '43'),
 ('Sonoma', 3.0, 1.0, 6.0, 2.0, 2.0, 2.0, 5.0, 5.0, 1.0, 3.0, 4.0, 2.0, '36'),
 ('Stanislaus',
  2.0,
  5.0,
  6.0,
  3.0,
  5.0,
  5.0,
  6.0,
  6.0,
  7.0,
  6.0,
  3.0,
  9.0,
  '63'),
 ('Sutter', 2.0, 0.0, 1.0, 0.0, 2.0, 3.0, 0.0, 5.0, 0.0, 5.0, 3.0, 1.0, '22'),
 ('Tehama', 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 3.0, 1.0, 2.0, 2.0, 3.0, '15'),
 ('Trinity', 0.0, 1.0, 0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 2.0, 1.0, 0.0, 1.0, '8'),
 ('Tulare', 3.0, 2.0, 7.0, 2.0, 4.0, 5.0, 4.0, 9.0, 8.0, 9.0, 2.0, 5.0, '60'),
 ('Tuolumne',
  4.0,
  1.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  2.0,
  1.0,
  0.0,
  1.0,
  '12'),
 ('Ventura', 1.0, 0.0, 4.0, 4.0, 9.0, 3.0, 5.0, 5.0, 3.0, 5.0, 1.0, 3.0, '43'),
 ('Yolo', 3.0, 1.0, 2.0, 2.0, 4.0, 2.0, 2.0, 2.0, 0.0, 2.0, 3.0, 1.0, '24'),
 ('Yuba', 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 0.0, '13'),
 ('Total',
  282.0,
  234.0,
  257.0,
  254.0,
  275.0,
  298.0,
  288.0,
  307.0,
  304.0,
  306.0,
  336.0,
  297.0,
  '3,438')]